// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// condition_cpp_predictors_scaling
List condition_cpp_predictors_scaling(List gene_conditions, List peak_conditions, IntegerVector tf_index, IntegerVector peak_index, double scale_floor);
RcppExport SEXP _Pando_condition_cpp_predictors_scaling(SEXP gene_conditionsSEXP, SEXP peak_conditionsSEXP, SEXP tf_indexSEXP, SEXP peak_indexSEXP, SEXP scale_floorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type gene_conditions(gene_conditionsSEXP);
    Rcpp::traits::input_parameter< List >::type peak_conditions(peak_conditionsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type tf_index(tf_indexSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type peak_index(peak_indexSEXP);
    Rcpp::traits::input_parameter< double >::type scale_floor(scale_floorSEXP);
    rcpp_result_gen = Rcpp::wrap(condition_cpp_predictors_scaling(gene_conditions, peak_conditions, tf_index, peak_index, scale_floor));
    return rcpp_result_gen;
END_RCPP
}
// condition_cpp_estar_solver
List condition_cpp_estar_solver(NumericMatrix H, NumericVector r, NumericVector information, double z, double solver_tol, int solver_max_iter, double solver_scale, double lipschitz);
RcppExport SEXP _Pando_condition_cpp_estar_solver(SEXP HSEXP, SEXP rSEXP, SEXP informationSEXP, SEXP zSEXP, SEXP solver_tolSEXP, SEXP solver_max_iterSEXP, SEXP solver_scaleSEXP, SEXP lipschitzSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type H(HSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type information(informationSEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type solver_tol(solver_tolSEXP);
    Rcpp::traits::input_parameter< int >::type solver_max_iter(solver_max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type solver_scale(solver_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type lipschitz(lipschitzSEXP);
    rcpp_result_gen = Rcpp::wrap(condition_cpp_estar_solver(H, r, information, z, solver_tol, solver_max_iter, solver_scale, lipschitz));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Pando_condition_cpp_predictors_scaling", (DL_FUNC) &_Pando_condition_cpp_predictors_scaling, 5},
    {"_Pando_condition_cpp_estar_solver", (DL_FUNC) &_Pando_condition_cpp_estar_solver, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_Pando(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
