// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 1F27D9A2-6A82-45D7-9E16-233B3A13F09C
#include <RcppEigen.h>
#include <Rcpp.h>
using namespace Rcpp;

Rcpp::List condition_fit_multitask_path_cpp(Rcpp::List,Rcpp::List,Rcpp::NumericVector,double,double,std::string,Rcpp::LogicalMatrix,int,double,double,bool);
RcppExport SEXP _Pando_condition_fit_multitask_path_cpp(SEXP a,SEXP b,SEXP c,SEXP d,SEXP e,SEXP f,SEXP g,SEXP h,SEXP i,SEXP j,SEXP k){
BEGIN_RCPP
Rcpp::RObject out;Rcpp::RNGScope scope;
out=Rcpp::wrap(condition_fit_multitask_path_cpp(
Rcpp::as<Rcpp::List>(a),Rcpp::as<Rcpp::List>(b),Rcpp::as<Rcpp::NumericVector>(c),
Rcpp::as<double>(d),Rcpp::as<double>(e),Rcpp::as<std::string>(f),
Rcpp::as<Rcpp::LogicalMatrix>(g),Rcpp::as<int>(h),Rcpp::as<double>(i),
Rcpp::as<double>(j),Rcpp::as<bool>(k)));return out;
END_RCPP
}

SEXP condition_product_matrix_cpp(SEXP,SEXP,Rcpp::IntegerVector,Rcpp::IntegerVector);
RcppExport SEXP _Pando_condition_product_matrix_cpp(SEXP a,SEXP b,SEXP c,SEXP d){
BEGIN_RCPP
Rcpp::RObject out;Rcpp::RNGScope scope;
out=condition_product_matrix_cpp(a,b,Rcpp::as<Rcpp::IntegerVector>(c),Rcpp::as<Rcpp::IntegerVector>(d));
return out;
END_RCPP
}

static const R_CallMethodDef CallEntries[]={
{"_Pando_condition_fit_multitask_path_cpp",(DL_FUNC)&_Pando_condition_fit_multitask_path_cpp,11},
{"_Pando_condition_product_matrix_cpp",(DL_FUNC)&_Pando_condition_product_matrix_cpp,4},
{NULL,NULL,0}};
RcppExport void R_init_Pando(DllInfo*dll){
R_registerRoutines(dll,NULL,CallEntries,NULL,NULL);
R_useDynamicSymbols(dll,FALSE);
}
