// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 1F27D9A2-6A82-45D7-9E16-233B3A13F09C

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

Rcpp::List condition_fit_multitask_path_cpp(Rcpp::List X_list, Rcpp::List y_list, Rcpp::NumericVector lambda, double alpha, double condition_mix, std::string condition_weight, Rcpp::LogicalMatrix coefficient_mask, int max_iter, double tol_objective, double tol_coef, bool keep_history);
RcppExport SEXP _Pando_condition_fit_multitask_path_cpp(SEXP X_listSEXP, SEXP y_listSEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP condition_mixSEXP, SEXP condition_weightSEXP, SEXP coefficient_maskSEXP, SEXP max_iterSEXP, SEXP tol_objectiveSEXP, SEXP tol_coefSEXP, SEXP keep_historySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type X_list(X_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type y_list(y_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type condition_mix(condition_mixSEXP);
    Rcpp::traits::input_parameter< std::string >::type condition_weight(condition_weightSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalMatrix >::type coefficient_mask(coefficient_maskSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol_objective(tol_objectiveSEXP);
    Rcpp::traits::input_parameter< double >::type tol_coef(tol_coefSEXP);
    Rcpp::traits::input_parameter< bool >::type keep_history(keep_historySEXP);
    rcpp_result_gen = Rcpp::wrap(condition_fit_multitask_path_cpp(X_list, y_list, lambda, alpha, condition_mix, condition_weight, coefficient_mask, max_iter, tol_objective, tol_coef, keep_history));
    return rcpp_result_gen;
END_RCPP
}

SEXP condition_product_matrix_cpp(SEXP left_matrix, SEXP right_matrix, Rcpp::IntegerVector left_index, Rcpp::IntegerVector right_index);
RcppExport SEXP _Pando_condition_product_matrix_cpp(SEXP left_matrixSEXP, SEXP right_matrixSEXP, SEXP left_indexSEXP, SEXP right_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type left_matrix(left_matrixSEXP);
    Rcpp::traits::input_parameter< SEXP >::type right_matrix(right_matrixSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type left_index(left_indexSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type right_index(right_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(condition_product_matrix_cpp(left_matrix, right_matrix, left_index, right_index));
    return rcpp_result_gen;
END_RCPP
}

Rcpp::List condition_refit_path_cpp(Rcpp::List beta_path, Rcpp::LogicalMatrix estimability_mask, Rcpp::NumericVector ridge, double active_tol, Rcpp::List cache, double tolerance);
RcppExport SEXP _Pando_condition_refit_path_cpp(SEXP beta_pathSEXP, SEXP estimability_maskSEXP, SEXP ridgeSEXP, SEXP active_tolSEXP, SEXP cacheSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type beta_path(beta_pathSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalMatrix >::type estimability_mask(estimability_maskSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ridge(ridgeSEXP);
    Rcpp::traits::input_parameter< double >::type active_tol(active_tolSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type cache(cacheSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(condition_refit_path_cpp(beta_path, estimability_mask, ridge, active_tol, cache, tolerance));
    return rcpp_result_gen;
END_RCPP
}


Rcpp::List condition_fit_target_engine_cpp(Rcpp::List X_list, Rcpp::List y_list, Rcpp::LogicalMatrix coefficient_mask, Rcpp::IntegerVector comparison_index, Rcpp::Nullable<Rcpp::NumericVector> lambda, bool lambda_auto, int nlambda, double lambda_min_ratio, double alpha, double condition_mix, double active_tol, Rcpp::List fold_plan, std::string lambda_selection, int max_iter, double tol_objective, double tol_coef, Rcpp::List engine_control);
RcppExport SEXP _Pando_condition_fit_target_engine_cpp(SEXP X_listSEXP, SEXP y_listSEXP, SEXP coefficient_maskSEXP, SEXP comparison_indexSEXP, SEXP lambdaSEXP, SEXP lambda_autoSEXP, SEXP nlambdaSEXP, SEXP lambda_min_ratioSEXP, SEXP alphaSEXP, SEXP condition_mixSEXP, SEXP active_tolSEXP, SEXP fold_planSEXP, SEXP lambda_selectionSEXP, SEXP max_iterSEXP, SEXP tol_objectiveSEXP, SEXP tol_coefSEXP, SEXP engine_controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type X_list(X_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type y_list(y_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalMatrix >::type coefficient_mask(coefficient_maskSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type comparison_index(comparison_indexSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type lambda_auto(lambda_autoSEXP);
    Rcpp::traits::input_parameter< int >::type nlambda(nlambdaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_min_ratio(lambda_min_ratioSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type condition_mix(condition_mixSEXP);
    Rcpp::traits::input_parameter< double >::type active_tol(active_tolSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type fold_plan(fold_planSEXP);
    Rcpp::traits::input_parameter< std::string >::type lambda_selection(lambda_selectionSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol_objective(tol_objectiveSEXP);
    Rcpp::traits::input_parameter< double >::type tol_coef(tol_coefSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type engine_control(engine_controlSEXP);
    rcpp_result_gen = Rcpp::wrap(condition_fit_target_engine_cpp(X_list, y_list, coefficient_mask, comparison_index, lambda, lambda_auto, nlambda, lambda_min_ratio, alpha, condition_mix, active_tol, fold_plan, lambda_selection, max_iter, tol_objective, tol_coef, engine_control));
    return rcpp_result_gen;
END_RCPP
}

Rcpp::List condition_native_self_test_cpp();
RcppExport SEXP _Pando_condition_native_self_test_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(condition_native_self_test_cpp());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Pando_condition_fit_multitask_path_cpp", (DL_FUNC) &_Pando_condition_fit_multitask_path_cpp, 11},
    {"_Pando_condition_product_matrix_cpp", (DL_FUNC) &_Pando_condition_product_matrix_cpp, 4},
    {"_Pando_condition_refit_path_cpp", (DL_FUNC) &_Pando_condition_refit_path_cpp, 6},
    {"_Pando_condition_fit_target_engine_cpp", (DL_FUNC) &_Pando_condition_fit_target_engine_cpp, 17},
    {"_Pando_condition_native_self_test_cpp", (DL_FUNC) &_Pando_condition_native_self_test_cpp, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_Pando(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
