# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 1F27D9A2-6A82-45D7-9E16-233B3A13F09C

.condition_fit_multitask_path_cpp <- function(X_list, y_list, lambda, alpha, condition_mix, condition_weight, coefficient_mask, max_iter, tol_objective, tol_coef, keep_history) {
    .Call(`_Pando_condition_fit_multitask_path_cpp`, X_list, y_list, lambda, alpha, condition_mix, condition_weight, coefficient_mask, max_iter, tol_objective, tol_coef, keep_history)
}

.condition_interaction_design_cpp <- function(tf_matrix, peak_matrix, tf_index, peak_index) {
    .Call(`_Pando_condition_interaction_design_cpp`, tf_matrix, peak_matrix, tf_index, peak_index)
}
