# Generated by using Rcpp::compileAttributes(); do not edit by hand
#
# The wrappers below deliberately resolve registered native routines at call
# time. Rcpp's default backtick bindings can be absent from a BiocParallel
# worker namespace even when the Pando DLL and registration table are loaded.
# Explicit registered-symbol lookup keeps PSOCK, forked, and restored-session
# workers on the same native ABI without enabling dynamic-symbol fallback.

.pando_registered_symbol <- function(symbol) {
    tryCatch(
        getNativeSymbolInfo(
            symbol,
            PACKAGE = "Pando",
            withRegistrationInfo = TRUE
        ),
        error = function(error) {
            stop(
                "Pando registered native routine `", symbol,
                "` is unavailable in this R process. Reinstall Pando and ",
                "restart the R session before running parallel GRN inference. ",
                "Original error: ", conditionMessage(error),
                call. = FALSE
            )
        }
    )
}

.pando_registered_call <- function(symbol, ...) {
    .Call(.pando_registered_symbol(symbol), ...)
}

.condition_fit_multitask_path_cpp <- function(X_list, y_list, lambda, alpha, condition_mix, condition_weight, coefficient_mask, max_iter, tol_objective, tol_coef, keep_history) {
    .pando_registered_call("_Pando_condition_fit_multitask_path_cpp", X_list, y_list, lambda, alpha, condition_mix, condition_weight, coefficient_mask, max_iter, tol_objective, tol_coef, keep_history)
}

.condition_product_matrix_cpp <- function(left_matrix, right_matrix, left_index, right_index) {
    .pando_registered_call("_Pando_condition_product_matrix_cpp", left_matrix, right_matrix, left_index, right_index)
}

.condition_refit_path_cpp <- function(beta_path, estimability_mask, ridge, active_tol, cache, tolerance) {
    .pando_registered_call("_Pando_condition_refit_path_cpp", beta_path, estimability_mask, ridge, active_tol, cache, tolerance)
}

.condition_fit_target_engine_cpp <- function(X_list, y_list, coefficient_mask, comparison_index, lambda, lambda_auto, nlambda, lambda_min_ratio, alpha, condition_mix, active_tol, fold_plan, lambda_selection, max_iter, tol_objective, tol_coef) {
    .pando_registered_call("_Pando_condition_fit_target_engine_cpp", X_list, y_list, coefficient_mask, comparison_index, lambda, lambda_auto, nlambda, lambda_min_ratio, alpha, condition_mix, active_tol, fold_plan, lambda_selection, max_iter, tol_objective, tol_coef)
}
